# Generated by Django 3.2.6 on 2021-12-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcoll', '0002_comment_composer_difficulty_favorite_period_piece_upvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='piece',
        ),
        migrations.AddField(
            model_name='favorite',
            name='composers',
            field=models.ManyToManyField(blank=True, to='classcoll.Composer'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='pieces',
            field=models.ManyToManyField(blank=True, to='classcoll.Piece'),
        ),
    ]
