# Generated by Django 3.2.6 on 2021-12-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcoll', '0003_auto_20211219_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='image',
            field=models.FileField(upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='source',
            field=models.FileField(upload_to='upload'),
        ),
    ]
