# Generated by Django 3.2.6 on 2021-12-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcoll', '0004_auto_20211221_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='piece',
            name='source',
            field=models.FileField(upload_to='upload/audio'),
        ),
    ]
