# Generated by Django 3.2.6 on 2021-12-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcoll', '0005_auto_20211222_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='source',
            field=models.FileField(upload_to='upload'),
        ),
    ]
