# Generated by Django 3.2.6 on 2021-12-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcoll', '0006_alter_piece_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='source',
            field=models.FileField(upload_to=''),
        ),
    ]
