# Generated by Django 3.2.6 on 2021-12-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcoll', '0007_alter_piece_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='composers',
            field=models.ManyToManyField(to='classcoll.Composer'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='pieces',
            field=models.ManyToManyField(to='classcoll.Piece'),
        ),
    ]
