# Generated by Django 3.2.6 on 2021-12-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcoll', '0008_auto_20211224_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='composers',
            field=models.ManyToManyField(related_name='composers', to='classcoll.Composer'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='pieces',
            field=models.ManyToManyField(related_name='pieces', to='classcoll.Piece'),
        ),
    ]
