# Generated by Django 3.2.6 on 2021-12-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classcoll', '0010_auto_20211224_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
