# Generated by Django 3.2.6 on 2021-12-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcoll', '0011_remove_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
